services:
# =========================
# ======= MANDATORY =======
# =========================

  mariadb:
    container_name: mariadb
    build: ./mariadb/
    image: mariadb
    networks:
      - inception
    env_file:
      - ./conf/env/.env
    expose:
      - ${DB_PORT}
    secrets:
      - db_root
      - db_user
    volumes:
      - db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "/usr/local/bin/mariadb_healthcheck.sh"]
      interval: 2s
      timeout: 2s
      retries: 10
      start_period: 5s
    restart: always

  wordpress:
    container_name: wordpress
    build: ./wordpress/
    image: wordpress
    volumes:
      - wp:/var/www/html
    networks:
      - inception
    env_file:
      - ./conf/env/.env
    secrets:
      - db_user
      - wp_admin
      - wp_user
    healthcheck:
      test: ["CMD", "cgi-fcgi", "-bind", "-connect", "127.0.0.1:9000"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 15s
    depends_on:
      mariadb:
        condition: service_healthy
      redis:
        condition: service_started
    restart: always

  nginx:
    container_name: nginx
    image: nginx
    build: ./nginx/
    volumes:
      - wp:/var/www/html
    ports:
      - 443:443
    networks:
      - inception
    depends_on:
      wordpress:
        condition: service_healthy
      adminer:
        condition: service_started
      static-site:
        condition: service_started
    restart: always

# =========================
# ========= BONUS =========
# =========================
  redis:
    container_name: redis
    image: redis
    build: ./bonus/redis/
    expose:
      - 6379
    networks:
      - inception
    restart: always

  adminer:
    container_name: adminer
    image: adminer
    build: ./bonus/adminer
    expose:
      - 8080
    networks:
      - inception
    restart: always

  static-site:
    container_name: static-site
    image: static-site
    build: ./bonus/static-site
    expose:
      - 8081
    networks:
      - inception
    volumes:
      - static:/var/www/static/
    restart: always
  ftp:
    container_name: ftp
    image: ftp
    build: ./bonus/ftp
    networks:
      - inception
    ports:
      - "21:21"
      - "60000-60005:60000-60005"
    volumes:
      - wp:/var/www/html
    depends_on:
      wordpress:
        condition: service_started
    restart: always

volumes:
  db:
    name: db_volume
    driver_opts:
      type: none
      o: bind
      device: /home/lflayeux/data/db
  wp:
    name: wp_volume
    driver_opts:
      type: none
      o: bind
      device: /home/lflayeux/data/wp
  static:
    name: static_volume
    driver_opts:
      type: none
      o: bind
      device: /home/lflayeux/data/static
secrets:
  db_root:
    file: ./conf/secrets/db_root.txt
  db_user:
    file: ./conf/secrets/db_user.txt
  wp_admin:
    file: ./conf/secrets/wp_admin.txt
  wp_user:
    file: ./conf/secrets/wp_user.txt

networks:
  inception:
    name: inception-network
    driver: bridge