# Connexion 

listen=YES
local_enable=YES
write_enable=YES

# Hardening user restriction

userlist_enable=YES
userlist_file=/etc/vsftpd/user_list
userlist_deny=NO

# Hardening isolement and root direcory

local_root=/var/www/html
chroot_local_user=YES
allow_writeable_chroot=YES
chroot_list_enable=NO

# Passif mode

pasv_enable=YES
pasv_min_port=60000
pasv_max_port=60005
pasv_address=0.0.0.0

seccomp_sandbox=NO
